import type { Metadata } from 'next';
import './globals.css';
import type { FC } from 'react';
import React from 'react';
import localFont from 'next/font/local';

const helvicaLight = localFont({
  src: [
    {
      path: '../../public/fonts/HelveticaNeue-Light.otf',
      weight: '300',
      style: 'normal',
    },
  ],
  variable: '--font-helvetica-light',
});

const helvicaMedium = localFont({
  src: [
    {
      path: '../../public/fonts/HelveticaNeue-Medium.otf',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--font-helvetica-medium',
});

const helvicaRoman = localFont({
  src: [
    {
      path: '../../public/fonts/HelveticaNeue-Roman.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-helvetica-roman',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={`${helvicaLight.variable} ${helvicaMedium.variable} ${helvicaRoman.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
};
export default RootLayout;
