import type { Metadata } from 'next';
import './globals.css';
import type { FC } from 'react';
import React from 'react';
import localFont from 'next/font/local';
import { Toaster } from 'react-hot-toast';

const helvetica = localFont({
  src: [
    {
      path: '../../public/fonts/HelveticaNeue-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/HelveticaNeue-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/HelveticaNeue-Roman.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-helvetica',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  return (
    <html lang="en">
      <Toaster position="bottom-right" />
      <body className={`${helvetica.className} antialiased`}>{children}</body>
    </html>
  );
};
export default RootLayout;
